# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-17 18:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_job_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='scheme',
        ),
    ]
