# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-18 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_region_scheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='prefix',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
