# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-23 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_job_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primerpair',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primer_pairs', to='home.Region'),
        ),
    ]
